--create table [#tempref_services_offered] (
--[Id] [smallint] identity,
--[service_parent] [smallint] NULL,
--[service_name] [nvarchar] (100) NULL,
--[starting_labor_cost] [decimal] (18,0) NULL,
--[is_active] [smallint] NULL);



set identity_insert [#tempref_services_offered] on;


insert [#tempref_services_offered] ([Id],[service_parent],[service_name],[starting_labor_cost],[is_active])
select 1,0,N'PREVENTIVE MAINTENANCE SERVICE',2500,1 UNION ALL
select 2,0,N'AIRCON SERVICES',0,1 UNION ALL
select 3,0,N'AUTOMATIC TRANSMISSION',0,1 UNION ALL
select 4,0,N'UNDER CHASSIS',0,1 UNION ALL
select 5,0,N'COOLING SYSTEM RESTORATION',0,1 UNION ALL
select 6,0,N'MAJOR WORK',0,1 UNION ALL
select 7,0,N'OTHER SERVICES/CONCERNS',0,1 UNION ALL
select 8,1,N'REPLACE OIL FILTER',0,1 UNION ALL
select 9,1,N'REPLACE FUEL FILTER',0,1 UNION ALL
select 10,1,N'REPLACE AIR FILTER',0,1 UNION ALL
select 11,1,N'REPLACE SPARK PLUG',0,1 UNION ALL
select 12,1,N'REPLACE CABIN FILTER',0,1 UNION ALL
select 13,1,N'REPLACE DIFFERENTIAL OIL',0,1 UNION ALL
select 14,1,N'REPLACE TRANSMISSION OIL',0,1 UNION ALL
select 15,1,N'REPLACE BRAKE FLUID',0,1 UNION ALL
select 16,1,N'REPLACE COOLANT',0,1 UNION ALL
select 17,1,N'INSPECT BRAKE PADS, LINING AND DRUM',0,1 UNION ALL
select 18,1,N'INSPECT/REPLACE BRAKE HOSE AND DISCS',0,1 UNION ALL
select 19,1,N'INSPECT/REPLACE HANDBRAKE AND GEARBOX',0,1 UNION ALL
select 20,1,N'INSPECT FRONT AND REAR SUSPENSION',0,1 UNION ALL
select 21,1,N'INSPECT BATTERY SYSTEM',0,1 UNION ALL
select 22,1,N'INSPECT/CONDITION DRIVEBELT',0,1 UNION ALL
select 23,1,N'FLUID FLUSHING (COOLANT, TRANNY, DIFFERENTIAL, POWER STEERING, BRAKE)',0,1 UNION ALL
select 24,1,N'ENGINE DETAILING',0,1 UNION ALL
select 25,2,N'AIRCON CLEANING',0,1 UNION ALL
select 26,2,N'REPLACE COMPRESSOR',0,1 UNION ALL
select 27,2,N'REPLACE CONDENSER',0,1 UNION ALL
select 28,2,N'REPLACE EVAPORATOR',0,1 UNION ALL
select 29,2,N'REPLACE AUX FAN',0,1 UNION ALL
select 30,2,N'REPLACE EXPANSION VALVE FRONT',0,1 UNION ALL
select 31,2,N'REPLACE EXPANSION VALVE REAR',0,1 UNION ALL
select 32,2,N'REPLACE FILTER DRIER',0,1 UNION ALL
select 33,2,N'REPLACE HIGH PRESSURE SWITCH',0,1 UNION ALL
select 34,2,N'REPLACE O-RING',0,1 UNION ALL
select 35,3,N'AT DIAGNOSIS',0,1 UNION ALL
select 36,3,N'REPLACE ATF FILTER',0,1 UNION ALL
select 37,3,N'REPLACE ATF FLUID',0,1 UNION ALL
select 38,4,N'REPLACE BALLJOINT',0,1 UNION ALL
select 39,4,N'REPLACE STABILIZER LINK',0,1 UNION ALL
select 40,4,N'REPLACE SHOCK ABSORBER',0,1 UNION ALL
select 41,4,N'REPLACE ENGINE SUPPORT',0,1 UNION ALL
select 42,4,N'REPLACE TRANSMISSION SUPPORT',0,1 UNION ALL
select 43,4,N'REPLACE TIE ROD',0,1 UNION ALL
select 44,4,N'REPLACE RACK AND PINION',0,1 UNION ALL
select 45,4,N'REPLACE CROSS JOINT',0,1 UNION ALL
select 46,5,N'RADIATOR CLEANING',0,1 UNION ALL
select 47,5,N'COOLANT FLUSHING',0,1 UNION ALL
select 48,5,N'INSPECT/REPLACE WATER PUMP',0,1 UNION ALL
select 49,5,N'INSPECT/REPLACE THERMOSTAT',0,1 UNION ALL
select 50,5,N'INSPECT/REPLACE RADIATOR HOSE',0,1 UNION ALL
select 51,5,N'SILICONE OIL REFILL',0,1 UNION ALL
select 52,5,N'REPLACE AUXILIARY FAN',0,1 UNION ALL
select 53,6,N'REPLACE CYLINDER HEAD GASKET',0,1 UNION ALL
select 54,6,N'REPLACE TIMING BELT',0,1 UNION ALL
select 55,6,N'REPLACE TIMING CHAIN',0,1 UNION ALL
select 56,6,N'REPLACE TENSIONER',0,1 UNION ALL
select 57,6,N'REPLACE IDLER BEARING',0,1 UNION ALL
select 58,6,N'REPLACE OCV VALVE',0,1 UNION ALL
select 59,6,N'REPLACE CAMSHAFT SENSOR',0,1 UNION ALL
select 60,6,N'REPLACE CRANKSHAFT SENSOR',0,1 UNION ALL
select 61,6,N'REPLACE PRIMARY/SECONDARY CLUTCH',0,1 UNION ALL
select 62,6,N'REPLACE CLUTCH DISC',0,1 UNION ALL
select 63,6,N'REPLACE CLUTCH COVER',0,1 UNION ALL
select 64,6,N'REPLACE RELEASE BEARING',0,1 UNION ALL
select 65,6,N'REPLACE FLYWHEEL',0,1 UNION ALL
select 66,6,N'REPLACE BRAKE DISC',0,1 UNION ALL
select 67,6,N'REPLACE BRAKE DRUM',0,1 UNION ALL
select 68,6,N'REPLACE HYDROLIC',0,1 UNION ALL
select 69,6,N'MACHINE SHOP JOBS',0,1 UNION ALL
select 70,6,N'VALVE CLEARANCE SETTING',0,1 UNION ALL
select 71,6,N'TOP OVERHAULING',0,1 UNION ALL
select 72,6,N'GENERAL OVERHAULING',0,1 UNION ALL
select 73,6,N'REPLACE CYLINDER HEAD GASKET',0,1 UNION ALL
select 74,6,N'REPLACE ROCKER ARM',0,1 UNION ALL
select 75,6,N'REPLACE CAMSHAFT',0,1 UNION ALL
select 76,6,N'REPLACE CRANKSHAFT',0,1 UNION ALL
select 77,6,N'REPLACE CONNECTING ROD',0,1 UNION ALL
select 78,6,N'REPLACE PISTON',0,1 UNION ALL
select 79,6,N'REPLACE PISTON RING',0,1 UNION ALL
select 80,6,N'REPLACE ENGINE BEARING',0,1 UNION ALL
select 81,6,N'PULL DOWN CRANKSHAFT PULLEY',0,1 UNION ALL
select 82,7,N'BIG JOBS',0,1 UNION ALL
select 83,7,N'ECU SCANNING',0,1;

set identity_insert [#tempref_services_offered] off;